force-app/main/default/objects/CMT_Deploy_Event__e/CMT_Deploy_Event__e.object-meta.xml
<CustomObject>
    <label>CMT Deploy Event</label>
    <pluralLabel>CMT Deploy Events</pluralLabel>
</CustomObject>

force-app/main/default/objects/CMT_Deploy_Event__e/fields/Successfully_Deployed__c.field-meta.xml
<CustomField>
    <fullName>Successfully_Deployed__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Successfully Deployed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/CMTDeployCallback.cls
/**
 * @description       : 
 * @author            : Ben Learn
 * @group             : 
 * @last modified on  : 03-29-2022
 * @last modified by  : Ben Learn
**/
public class CMTDeployCallback implements Metadata.DeployCallback {
    public void handleResult(Metadata.DeployResult result, Metadata.DeployCallbackContext context) {
        CMT_Deploy_Event__e cmtDeployEvent = new CMT_Deploy_Event__e();

        if(result.status == Metadata.DeployStatus.SUCCEEDED) {
            cmtDeployEvent.Successfully_Deployed__c = true;
        } else {
            cmtDeployEvent.Successfully_Deployed__c = false;
            cmtDeployEvent.Error_Message__c = result.errorMessage;
        }

        EventBus.publish(cmtDeployEvent);
    }
}